services:
  vllm:
    image: vllm/vllm-openai:latest
    command: --model facebook/opt-125m
    environment:
      - HUGGING_FACE_HUB_TOKEN=
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ipc: host



  private-gpt:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: vllm
      PGPT_MODE: openailike
    depends_on:
      - vllm
